### ISSUE TITLE
test out jupyterlab-myst

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/xarray-tutorial#115]
https://github.com/executablebooks/jupyterlab-myst

This would allow us to use myst syntax for nice rendering in Jupyter Lab and the JupyterBook deployment.

 I see @scottyhq  has already opened an issue there :)

**Comment by scottyhq** [comment]
this has come a long way over the last year and definitely worth trying again! https://executablebooks.org/en/latest/blog/2023-02-09-announce-mystjs/#myst-will-have-first-class-support-in-javascript

**Comment by dcherian** [comment]
Can we get this added to the env soon please. I'm using it in #180

**Comment by rowanc1** [comment]
Looking forward to your feedback on the myst plugin!! It now works in JupyterLab v4 and supports a few more jupyterbook directives like glossaries, terms, exercises, and proofs. Let us know what else you all need! :)

**Comment by dcherian** [comment]
I'm excited to try out Exercises. Is that supported on the sphinx build too?

**Comment by rowanc1** [comment]
Yep!
- jupyterlab verion: https://mystmd.org/guide/exercises
- sphinx version: https://ebp-sphinx-exercise.readthedocs.io/en/latest/
