### ISSUE TITLE
Finish Xarray Ecosystem notebook

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/xarray-tutorial#116]

**Comment by dcherian** [comment]
@TomNicholas can you create some material showcasing the "Xarray ecosystem" and present it at the SciPy tutorial?

Our thought was to pick 2-4 packages and do quick demos, e.g. hvplot, rioxarray, pint-xarray, cf-xarray. These 4 would illustrate plotting, file handling, duck array handling, attribute handling which is a nice spread of topics.

**Comment by dcherian** [comment]
Just remembered I did a version of this a while ago: https://tutorial.xarray.dev/overview/xarray-in-45-min.html#the-scientific-python-ecosystem .

**Comment by scottyhq** [comment]
closed by #123
