### ISSUE TITLE
Finish "cleaning up real data"

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/xarray-tutorial#117]
- [x] Once you get it to 50MB or so, rename to “[ASE_ice_velocity.nc](http://ase_ice_velocity.nc/)”` and open a pull request adding it to https://github.com/pydata/xarray-data. This will let us use xr.tutorial.open_dataset("ASE_ice_velocity") in the tutorial. Add a description attribute describing your processing steps. 
- [x] Then I think you should open a PR adding your netcdf_example1 to xarray_tutorial. with file path data_cleaning/ice_velocity.ipynb . For now, I would add an entry in _toc.yml under Intermediate.
- [x] Final step will be to add an entry in the docstring for `xarray.tutorial.open_dataset`. You can use [this PR](https://github.com/pydata/xarray/pull/6719) for reference
- [x] Add entry in `scipy-2022/readme.md`

**Comment by scottyhq** [comment]
I think the idea was something along the lines of this example where the default xr.open_dataset() works but you need to rearrange dimensions and how metadata is stored https://gis.stackexchange.com/a/345697/144357 (from rioxarray docs https://corteva.github.io/rioxarray/stable/examples/examples.html)...

**Comment by e-marshall** [comment]
Had we talked about my short hdf5 example being used for this ? Happy to improve it/get it ready for the tutorial if so

**Comment by e-marshall** [comment]
I added dataset to xarray-data in https://github.com/pydata/xarray/pull/6753 and made some updates to the ice_velocity.ipynb with operations broken out into separate steps and more explanation, it should be under https://github.com/xarray-contrib/xarray-tutorial/pull/122, happy to make more changes to the notebook though, I think the `scipy-2022/readme.md` was updated in https://github.com/xarray-contrib/xarray-tutorial/pull/122 as well?
