### ISSUE TITLE
missing binder links

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/xarray-tutorial#118]
On Firefox + MacOS I don't see the binder launch button in the top:

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/2448579/176331730-ed3767f9-344e-449c-8557-bc0c7aea1b30.png">

**Comment by scottyhq** [comment]
```
"metadata": {
  "kernelspec": {
   },
```
An empty dictionary doesn't work b/c `jb build` runs `nbformat` to check metadata tags:
```pytb
ERROR: Notebook is invalid after preprocessor <nbconvert.preprocessors.tagremove.TagRemovePreprocessor object at 0x112c54a30>

Exception occurred:
  File "/Users/scott/miniconda3/envs/xarray-tutorial/lib/python3.10/site-packages/nbformat/validator.py", line 302, in validate
    raise error
nbformat.validator.NotebookValidationError: data.metadata.kernelspec must contain ['name', 'display_name'] properties

Failed validating <unset> in notebook['data']['metadata']:
```

**Comment by scottyhq** [comment]
Seems that simply waiting has fixed this one :) Maybe bumping jupyterbook versions, but the rocket ship binder launch buttons are back!
