### ISSUE TITLE
Issue on page /fundamentals/01.1_creating_data_structures.html

### ISSUE THREAD

**Issue by colettembrown** [xarray-contrib/xarray-tutorial#139]
On the website version of fundamentals, the "Data Variables" section accurately reflects what the student should know at this point. On the version downloaded from GitHub, there are 5 "Dimensions" listed: (latitude: 180longitude: 360lon: 53time: 2920lat: 25) and the "latitude" and "longitude" don't match the "lat" and "lon" in length or values. This issue of 5 dimensions continues on this page up until the "Exercises" section.

**Comment by dcherian** [comment]
> On the version downloaded from GitHub,

By this do you mean that you cloned this repository and executed that notebook?

**Comment by colettembrown** [comment]
> 

Yes

**Comment by dcherian** [comment]
Hmm.. I just ran that notebook locally and I don't see any 5d variables:

<img width="871" alt="image" src="https://user-images.githubusercontent.com/2448579/184019995-f5693abc-6f12-4bee-97f0-d332113a0a3b.png">

**Comment by colettembrown** [comment]
Yes – I just reran that notebook locally and it doesn't have the same
error. Not sure what happened.

**Comment by colettembrown** [comment]
Sorry, I meant that I fixed it on my local machine and I ran it and got the
same output as what's visible in your screenshot. The bug must be fixed.
Thank you!
