### ISSUE TITLE
hvPlot automatic color range

### ISSUE THREAD

**Issue by mdtanker** [xarray-contrib/xarray-tutorial#141]
Hi, I was looking through the [tutorial on plotting with hvplot](https://tutorial.xarray.dev/intermediate/hvplot.html) and had a question. Is there is a way of having the range of colors be automatically set to the zoom-extent for an interactive hvplot? Ideally, as you zoom in on a grid, the color scale would adjust to the local min/max. 

I can ask this over at [hvPlot](https://github.com/holoviz/hvplot) if that's more suitable.

**Comment by dcherian** [comment]
Yes please ask over at hvplot. :)
