### ISSUE TITLE
add an index or overview notebook for binder.

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/xarray-tutorial#153]

**Comment by scottyhq** [comment]
The current README markdown badge link points to `overview/fundamental-path/index.ipynb`:

https://mybinder.org/v2/gh/xarray-contrib/xarray-tutorial/HEAD?labpath=overview/fundamental-path/index.ipynb

The link can be modified to point at other notebooks in the repo like `overview/intermediate-path/index.ipynb`
