### ISSUE TITLE
feedback on "high-level computation patterns"

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/xarray-tutorial#166]
- @scottyhq points out that we should address that new users start by writing loops, we should encourage them to think of converting loops to these higher level helpers
- @JessicaS11 points out that these high level objects are hard to debug and understand. So some more intro material would be useful.

**Comment by keewis** [comment]
see pydata/xarray#7641 for an example for the conversion from loops to `groupby`.

The intro material should include tips on how to visualize those high-level objects (like, use `.construct` for `rolling` or call `dict` on `groupby` objects). I find that looking at a small sample of what they contain really helps when trying to come up with ways to transform the high-level object back to a `Dataset` / `DataArray`.

Also, maybe this is something for the main repository, but calling `arr.rolling(...).construct("window_dim").isel(...)` to get something that is easy to understand might be a bit much to write, so we probably should modify the `repr` of those objects to be a bit more informative?

**Comment by dcherian** [comment]
Just chatted with @maxrjones .

Another concept  to emphasize with rolling is views vs copies after calling `.construct`. And that if you have a vectorize-able function calling it on the output of `.construct` is probably a lot better than using `Rolling.__iter__`

**Comment by DOptimusPrime** [comment]
You can also check the my links. We have used some of Xarray high computational patterns. I will be posting some more of my work which combine xarray with other packages like gdal
