### ISSUE TITLE
timing and coordination for tutorial

### ISSUE THREAD

**Issue by rabernat** [xarray-contrib/xarray-tutorial#17]
I received the calendar invite for the scipy tutorial. Do we have any other logistics to discuss? Do we want to have a pre-tutorial meeting to rehearse and make sure everything flows together? Or am I overthinking it...

**Comment by jhamman** [comment]
Yes! Crunch time! Here's my run down of what is left to do and how we should break down the presentation time:

## TODOs

1. Xarray and Dask Notebook (#7) [high-priority]
2. Make formatting and style consistent across notebooks [medium-priority]
3. Add in-line exercises to all notebooks (like #18) [high-priority]
4. Add links to self-guided exercises to intro notebook [high-priority] 

## Schedule

0. Logistics [@jhamman]
1. Introduction / Data structures [@jhamman]
2. Working with labeled data [@rabernat]
3. Computation with Xarray [@rabernat]
4. Plotting and Visualization [@dcherian]
5. Introduction to Dask [@jhamman]
6. Dask and Xarray [@dcherian]
7. Pointers to self-guided exercises [@rabernat]

@shoyer and @keewis, I don't remember if either of you are planning to be there in person so I've left you off the live roster but feel free to speak up if you'd like to grab a section of the schedule.

**Comment by jhamman** [comment]
I'm going to start working on the 2nd and 4th todo items now.

**Comment by jhamman** [comment]
Chatted with @dcherian today. For those that can make it, let's plan to grab the 30 minutes prior to the xarray bi-weekly dev meeting to sync on any final issues. I'll send a calendar invite shortly for the meeting. https://whereby.com/xarray

**Comment by rabernat** [comment]
I’m unclear on what is required for item 7. 

Due to child care constraints, I’m going to have to be done by 1pm ET, 1:30 at the latest.

I’m not sure if I can join the call tomorrow as I’m technically on vacation. I’ll do my best.

**Comment by shoyer** [comment]
I've blocked out time to attend the tutorial in person to help out, though there is another meeting at 1pm ET that I'd like to attend it possible.

**Comment by jhamman** [comment]
@rabernat - This is what we proposed: 

```
## Self-guided exercises
1. Xarray workflow examples
  - Ocean surface temperature variability
  - Meteorological data analysis over the United States
2. Xarray+Dask workflow examples
  - Sea level rise analysis
  - Meteorological downscaling using Xarray, Dask, and scikit-learn
```

I think we just want to point to a few quality binders with real-world demos. If others can help curate the list, I can add them to the introduction notebook.

**Comment by rabernat** [comment]
I have two homework assignments I can share!

- https://earth-env-data-science.github.io/assignments/basic_xarray.html
- https://earth-env-data-science.github.io/assignments/xarray_groupby.html

**Comment by rabernat** [comment]
all times central:

- 9-9:10: Logistics [@jhamman]
  - Walk through tutorial structure
  - Explain binder
  - Explain how to run locally
- 9:10-9:30: Introduction / Data structures [@jhamman]
- 9:30-9:40: Break / Q&A
- 9:40-10:00: Working with labeled data [@rabernat]
- 10:00-10:10: Break / Q&A
- 10:10-10:40: Computation with Xarray [@rabernat]
- 10:40-11:00: Break / Q&A
- 11:00-11:30: Plotting and Visualization [@dcherian]
- 11:30-11:40: Break / Q&A
- 11:40-12:00: Introduction to Dask [@jhamman]
- 12:00-12:10: Break / Q&A
- 12:10-12:30: Dask and Xarray [@dcherian]
- 12:30-1:00: Break / Q&A
- Pointers to self-guided exercises [@jhamman / all]

**Comment by jhamman** [comment]
I'm waiting in the setup room for the tutorial now. I'll also keep Xarray's [Gitter](https://gitter.im/pydata/xarray?source=orgpage) page open in case quick chats are needed. Tutorial is looking great folks, thanks all for pulling it together.
