### ISSUE TITLE
Add general codespaces setup to README.md

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/xarray-tutorial#185]
Add a badge here:
<img width="805" alt="image" src="https://github.com/xarray-contrib/xarray-tutorial/assets/2448579/8c9208df-1d6e-4a3e-b36b-a5554a2c79f0">

**Comment by dcherian** [comment]
I think opening up jupyterlab to the fundamental learning path or "xarray in 45 minutes" would be great. I think it would mostly be used by "new users"

**Comment by lsetiawan** [comment]
Done in https://github.com/xarray-contrib/xarray-tutorial/pull/198
