### ISSUE TITLE
Complete xarray and dask notebook

### ISSUE THREAD

**Issue by jhamman** [xarray-contrib/xarray-tutorial#3]

**Comment by rabernat** [comment]
I just found this repo. Do we want to use it for AGU?

**Comment by jhamman** [comment]
Not really. I'm thinking this repo should be more like dask-examples. For the AGU tutorial, i suggest we start with https://github.com/pangeo-data/pangeo-tutorial-sea-2018. I'll open an issue there.

**Comment by scottyhq** [comment]
https://tutorial.xarray.dev/scipy-tutorial/05_intro_to_dask.html
