### ISSUE TITLE
 How to use xarray to convert .shrunk or .data format to .netcdf format?

### ISSUE THREAD

**Issue by csy0101** [xarray-contrib/xarray-tutorial#35]
I downloaded the output file of llc4320, but it can't be read. In llcread, it says to use xarray to convert the file to netcdf format. So how do you do it?

**Comment by keewis** [comment]
there's not much we can help you with since there's a lot of information missing. This is also not the place to ask this kind of question so I'm closing, but feel free to open a new issue on the [main repository](https://github.com/pydata/xarray)
