### ISSUE TITLE
Scipy2022 workshop and repository organization

### ISSUE THREAD

**Issue by scottyhq** [xarray-contrib/xarray-tutorial#53]
Discussed recently with @kmpaul @dcherian @JessicaS11 as we ramp up for a Scipy2022 tutorial, we're thinking of various possibilities for synthesizing existing content in this repository. Hopefully I accurately capture everything from that discussion below, it will be a bit lengthy!

The main question is *should this repository be 1. a collection of stand-alone tutorials that are snapshots in time, or 2. a single general xarray tutorial* that gets updated over time? Also want to link to some past discussion of xarray tutorials with @rabernat and @TomNicholas in https://github.com/pydata/xarray/issues/3564 

* option 1: we add a `scipy2022` subfolder with all content for a 4 hour workshop, and render it on the website
  (+) minimal changes to current setup
  (+) each event's content is self-contained
  (-) duplicated and outdated content accumulates over time
  (-) a user finding this repository or the rendered website has difficulty navigating the content

* option 2: we synthesize the generic content under "fundamentals" and add a "workshops" section on the left sidebar for event-specific content (JupyterBook, or stick with current sphinx theme on read-the-docs)
  (+) no proliferation of many tutorial subfolders or repositories with repetitive content
  (-) content from past events would be modified removed or reorganized (but tags could be used to make it possible to return to past states)

Some other general design goals that came up:
1. compatible with mybinder.org (preferred cloud infrastructure for workshops)
1. someone arriving at https://xarray-contrib.github.io/xarray-tutorial finds it easy to navigate the content (whether or not they are participating in a workshop)
1. what is here is not repetitive and complementary to what's in the current xarray documentation https://docs.xarray.dev/en/stable/tutorials-and-videos.html
1. not focused on any particular scientific domain
   1. organize domain-specific (geoscience, astronomy, finance) content as subchapters or link out to other domain-specific xarray content (https://foundations.projectpythia.org/landing-page.html) 
1. follow best-practices in tutorial design (https://diataxis.fr/tutorials/, https://guidebook.hackweek.io/resources/tutorial-resources.html) 

Any addition thoughts, questions, concerns? Please add comments!

**Comment by dcherian** [comment]
I like  option 2. 

> what is here is not repetitive and complementary to what's in the current xarray documentation [docs.xarray.dev/en/stable/tutorials-and-videos.html](https://docs.xarray.dev/en/stable/tutorials-and-videos.html)

I think we can just change that sidebar link to point to this  repo once everything is cleaned up. That page is mostly a Youtube playlist.

> not focused on any particular scientific domain. organize domain-specific (geoscience, astronomy, finance) content as subchapters or link out to other domain-specific xarray content

:+1: This could a  top-level heading like "fundamentals" and "workshops". We  could call it "Domain-specific  examples" and follow @rabernat's suggestion in https://github.com/pydata/xarray/issues/3564:

>  Each tutorial would cover the same core elements (loading data, indexing, aligning, grouping, computations, plotting, etc.), but using a familiar, real dataset, rather than the generic, made-up ones in our current docs.

**Comment by dcherian** [comment]
Notes from meeting:
1. @andersy005  has created a curated Youtube channel (I think this exists) + close interlinking of video+notebooks. We could have the tutorials more prominent in the landing page on the long term.
2. General consensus about maintaining "canonical versions" of notebook + updating styling and infrastructure. 
3. Support for adding domain-specific examples under tutorials.

**Comment by andersy005** [comment]
the Youtube channel resides here: https://www.youtube.com/channel/UCBlxVSA6xQXeb-i4GgTlO7g. so far, it only has curated playlists.
