### ISSUE TITLE
xarray and dask 2

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/xarray-tutorial#7]
- [ ] Parallel/streaming/lazy computation using dask.array with Xarray
- [ ] Reading and writing data with Dask and Xarray
- [ ] Automatic parallelization with apply_ufunc and map_blocks

**Comment by jhamman** [comment]
@rabernat or @dcherian - any progress on this notebook? I added a blank placeholder today to get the docs building but we should really get this added asap.

**Comment by rabernat** [comment]
I have some notes on this here: https://earth-env-data-science.github.io/lectures/dask/dask_arrays.html (github here: https://github.com/earth-env-data-science/earth-env-data-science-book/blob/master/content/lectures/dask/dask_arrays.ipynb)

Other than the tutorial on Thursday, I am on vacation this week, so don't really have much time to spend. @dcherian - hopefully you can that and expand on it a bit.

**Comment by dcherian** [comment]
I'm working on it now.
