### ISSUE TITLE
Consistent format for Exercise Q&A

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/xarray-tutorial#88]
Is there a nice way to have a hidden "answer" cell for our exercises?

**Comment by scottyhq** [comment]
@dcherian I actually played around with this last week and accidentally opened the PR on my fork! https://github.com/scottyhq/xarray-tutorial/pull/5

But, I think the most straightforward solution is to have a *separate header markdown cell* (### Soluton X) and use the 'hide-output' metadata tag on the solution cell to have a toggle button on the rendered website

**Comment by dcherian** [comment]
Nice. The rendering in Jupyterlab is unfortunate. But it is a major "mode of consumption" for this material. So perhaps we go with something that renders well in Jupyterlab.

**Comment by scottyhq** [comment]
I think we should bumpy to jupyterlab-myst 2.0 and use the exercise directive across all tutorials as documented here https://mystmd.org/guide/exercises#hiding-directive-content !

**Comment by dcherian** [comment]
I think the CSS could be improved a bit but maybe good enough  for now?

<img width="805" alt="image" src="https://github.com/xarray-contrib/xarray-tutorial/assets/2448579/85282346-a7ff-4b97-8359-928fccd7650e">

**Comment by dcherian** [comment]
This is how it looks if I use the "tip" syntax
````
```{tip} Exercise
```
````

<img width="940" alt="image" src="https://github.com/xarray-contrib/xarray-tutorial/assets/2448579/95e7e133-18c7-40b6-8311-d32e3a6dbbc2">

**Comment by dcherian** [comment]
OTOH I guess we can use the new syntax and gain fewer edits in the future...

Will need to install `sphinx-exercise` too : https://ebp-sphinx-exercise.readthedocs.io/en/latest/

**Comment by scottyhq** [comment]
> This is how it looks if I use the "tip" syntax

In the notebook, I really like that appearance, but unfortunately the jupyterbook rendering is inconsistent:

<img width="796" alt="Screenshot 2023-06-26 at 8 47 38 PM" src="https://github.com/xarray-contrib/xarray-tutorial/assets/3924836/15a90f08-8973-4498-9f72-81a2b1c76df3">

https://xarray-contrib-xarray-tutorial-preview-pr-180.surge.sh/advanced/apply_ufunc/simple_dask_apply_ufunc.html#dimensions-that-change-size

**Comment by scottyhq** [comment]
Just wanted to note that jupyterlab-myst 2.0 is nicely solving the problem of a consistent appearance of notebooks in jupyterlab and as rendered by jupyter book. 

But sharing the notebook via other commonly used rendering services (github, https://nbviewer.org, https://notebooksharing.space) or IDEs (VSCode) won't style things correctly. But I think it's fine to have this repository focus on jupyterlab+jupyterbook!

**Comment by dcherian** [comment]
Actually i have jupyterlab < 4, so the rendering might just be because we need jupyterlab > 4. The rendered version on the web is quite nice!

<img width="940" alt="image" src="https://github.com/xarray-contrib/xarray-tutorial/assets/2448579/1c34a9aa-b8b3-4584-8944-3fff7ddffadd">

**Comment by scottyhq** [comment]
closed by #270
