### ISSUE TITLE
Fix up 'working with labeled data'

### ISSUE THREAD

**Issue by scottyhq** [xarray-contrib/xarray-tutorial#91]
https://tutorial.xarray.dev/fundamentals/02.1_working_with_labeled_data.html 

- [x] learning goals no longer deals w/ interpolation (split into another notebook)
- [x] fix different selection techniques to actually get the same value! 
- [x] improve exercise formatting
- [ ] describe basic plotting

@dcherian looking at this notebook and others, I'm tempted to change the example data values a bit to not use `np.random.randn(3, 4)` and instead use something that is *easier to visualize both difference in values and dimensions*, so for example `np.arange(10).reshape(2,5)`. thoughts?

**Comment by dcherian** [comment]
The later material in "computation" makes heavy use of plotting to illustrate output. I think we should have a super basic plotting intro in this section. (I've added it to the checklist but please remove if you disagree)

**Comment by scottyhq** [comment]
> The later material in "computation" makes heavy use of plotting to illustrate output. I think we should have a super basic plotting intro in this section. (I've added it to the checklist but please remove if you disagree) 

Sounds good! tackling this now.
