### ISSUE TITLE
Customize binder startup to show notebook index

### ISSUE THREAD

**Issue by scottyhq** [xarray-contrib/xarray-tutorial#95]
If someone uses a standard binder link for this repository (https://mybinder.org/v2/gh/xarray-contrib/xarray-tutorial/HEAD, or the badge in this readme or at https://tutorial.xarray.dev/overview/get-started.html), they end up seeing a rather blank jupyterlab with all the files in this repository.

It would be nice to open an index of notebooks like an index.md with one sentence descriptions like on the planetray computer. (see https://github.com/microsoft/planetary-computer-hub/blob/0d01fd87c016ad142a4b25067455a07c32e053bd/helm/chart/files/etc/singleuser/k8s-lifecycle-hook-post-start.sh)

Even more workspace customization is possible (e.g. automatically open dask labextension or other widgets, multiple notebooks, etc: https://github.com/dask/dask-examples/blob/main/binder/start)

**Comment by dcherian** [comment]
> automatically open dask labextension or other widgets, multiple notebooks, etc

We used to have some of this stuff: https://github.com/xarray-contrib/xarray-tutorial/commit/9e8767e355825381c6c41ebd7c1aa5c5f862f2e2#diff-9345de5f226db533cc81eb4d574f437e283e6585541d7fb7b396753ddc700390
